--- 
abstract: query mirrors status from mirrors.cpan.org
author: 
  - shelling <shelling@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: mit
name: CPAN-MirrorStatus
requires: 
  Rubyish::Attribute: 0
  self: 0
version: 0.02_01
